spring:
  application:
    name: cards
  profiles:
    active: production
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/accountsapp?serverTimezone=Europe/Warsaw&userSSL=False
    username: admin
    password: admin
    ddl-mode: create
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

# ACTUATOR INFO
info:
  app:
    name: "Cards"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}

management:
  info:
    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client: ${eureka-client}

application:
  allow-get-cards: ${cards.allow-get-cards}

feign:
  hystrix:
    enabled: true

#server:
#  port: 9997